#
# @author Greg PFISTER <greg@oskey.io>
# @copyright (c) 2022 OSkey.io. All rights reserved.
# @license SEE LICENSE IN LICENSE.md
#

version: '3.9'

# Services
services:
  firebase:
    container_name: firebase-oskey-example
    build:
      dockerfile: Dockerfile
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
      - '19003:19003'
      - '19004:19004'
      - '19005:19005'
      - '19006:19006'
    volumes:
      - ..:/workspace
      - firebase-devenv-home:/home
    networks:
      - oskey-dev

volumes:
  firebase-devenv-home:
    name: firebase-devenv-home-oskey-example

networks:
  oskey-dev:
    name: oskey-example
