#
# firebase-oskey-example
# Copyright (c) 2021-2023, OSkey SAS. MIT License.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

name: Build
on:
  workflow_call:
jobs:
  build:
    name: Build firebase-oskey-example
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node 18.15.0
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
          cache: 'npm'
      - name: 'Firebase: Install dependencies'
        run: |
          npm ci && \
          tar cvfz firebase-tools.tar.gz node_modules
      - name: 'Functions: Install dependencies, lint and build'
        run: |
          (cd functions; npm ci && npm run lint && npm run build) && \
          tar cvfz functions.tar.gz functions
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          retention-days: 1
          path: |
            firebase-tools.tar.gz
            functions.tar.gz

# End
