#
# firebase-oskey-example
# Copyright (c) 2021-2023, OSkey SAS. MIT License.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# Continuous delivery - Build, test and publish npm package on release creation
name: CD

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: (cd functions; npm ci && npm run lint && npm run build)
      - run: (cd test; npm ci && npm run lint)
      - run: PATH=$PATH:./.devcontainer firebase-cli use local
      - run: PATH=$PATH:./.devcontainer npm run test:ci:json
        env:
          FIREBASE_TOKEN: ${{ secrets.firebase_token }}

  deploy-firebase:
    needs: test
    runs-on: ubuntu-22.04
    environment:
      name: production
      url: https://example.oskey.dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: (cd functions; npm ci && npm run lint)
      - run: PATH=$PATH:./.devcontainer firebase-cli use local
      - run: PATH=$PATH:./.devcontainer npm run deploy:ci:part1
      - run: PATH=$PATH:./.devcontainer npm run deploy:ci:part2
        env:
          FIREBASE_TOKEN: ${{ secrets.firebase_token }}
