#
# firebase-oskey-example
# Copyright (c) 2021-2023, OSkey SAS. MIT License.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

name: Deploy to production
on:
  workflow_call:
jobs:
  deploy:
    name: Deploy firebase-oskey-example to production
    runs-on: ubuntu-22.04
    environment:
      name: production
      url: https://example.oskey.dev
    env:
      GCLOUD_PROJECT: ${{ vars.GCLOUD_PROJECT }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials.json
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node 18.15.0
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
          cache: 'npm'
      - name: Artifact download
        uses: actions/download-artifact@v3
        with:
          name: build-output
      - name: Unpack
        run: |
          tar xvfz firebase-tools.tar.gz && \
          rm -rf functions && tar xvfz functions.tar.gz
      - name: Set google credentials
        run: echo $GOOGLE_APPLICATION_CREDENTIALS_PROD_BASE64 | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
        env:
          GOOGLE_APPLICATION_CREDENTIALS_PROD_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_PROD_BASE64 }}
      - name: Set to prod project
        run: firebase-cli use prod
      - name: Deploy to prod part 1
        run: npm run deploy:ci:part1
      - name: Deploy to prod part 2
        run: npm run deploy:ci:part2
# End
